default:
    outputs:
        dev:
            dbname: airflow
            host: postgres
            password: '{{ env_var(''COSMOS_CONN_POSTGRES_PASSWORD'') }}'
            port: 5432
            schema: public
            type: postgres
            user: airflow
    target: dev
