jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: pg_password
      port: 5432
      dbname: airflow
      schema: public
      threads: 4
